= Contribution Guide

🎉 Thanks for taking the time to contribute! 🎉 Contributions are welcome from
anyone on the internet, and even the smallest of fixes are appreciated!

The following is a set of guidelines for contributing. These are mostly
guidelines, not rules. Use your best judgment, and feel free to propose changes
to this document in a pull request.

== Getting started

1. Fork https://github.com/keep-network/keep-common[`keep-network/keep-common`]
2. Clone your fork
3. Follow the
https://github.com/keep-network/keep-common/blob/main/README.adoc[installation
steps] in the README.
4. Enable
https://help.github.com/en/articles/about-commit-signature-verification[commit
signing].
5. Open a PR against the `main` branch and describe the change you are intending
to undertake in the PR description.

Before marking the PR as ready for review, make sure your changes have
sufficient test coverage (e.g regression tests have been added for bug fixes,
unit tests for new features)

=== Continuous Integration

Keep uses
https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions[Github
Actions] for continuous integration. All workflows must be green to merge a PR.
