version: 2.1

executors:
  docker-go:
    docker:
      - image: circleci/golang:1.13

jobs:
# GitHub Actions equivalent of this job (.github/workflows/client.yml)
# has been created as part of work on RFC-18
  test-go:
    executor: docker-go
    steps:
      - checkout
      - run:
          name: Create test directories
          command: |
            mkdir -p test-results/keep-common
      - run:
          name: Run Go generators
          command: |
            go generate ./.../gen
      - run:
          name: Run Go tests
          command: |
            gotestsum --junitfile test-results/keep-common/unit-tests.xml
      - store_test_results:
          path: test-results
workflows:
  version: 2
  test:
    jobs:
      - test-go
