name: Go

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  client-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.13.x"

      - name: Run Go generators
        run: go generate ./.../gen

      - name: Build Go
        run: go build ./...

      - name: Install gotestsum
        run: go get gotest.tools/gotestsum

      - name: Run Go tests
        run: gotestsum

  client-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          args: ./...

  client-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Go
        uses: keep-network/ci/actions/golint-action@move-actions-to-ci # TODO: change to @v1 before merging to main