name: Go

#TODO: extend the conditions once workflow gets tested together with other workflows
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  client-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.13.x"

      - name: Run Go generators
        run: go generate ./.../gen

      - name: Build Go
        run: go build ./...

      - name: Create test results directory
        run: mkdir test-results

      - name: Install gotestsum
        run: go get gotest.tools/gotestsum

      - name: Run Go tests
        run: gotestsum --junitfile test-results/unit-tests.xml

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./test-results/unit-tests.xml
          check_name: Go Test Results # name under which test results will be presented in GitHub (optional)
          comment_on_pr: false # turns off commenting on Pull Requests

  client-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          args: ./...